[package]
name = "nixwebring-server"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.8"
ntex = { version = "2.17.0", features = [ "tokio", "rustls" ] }
ntex-files = "2.1.0"
rand = "0.9.2"
zasa = { version = "0.7.0", features = [ "derive" ] }
